### ISSUE TITLE
Symbolic link is not an actual file 	¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by SilentAutomaton** [Qufyy/obs-pipewire-audio-capture#1]
There is only symbolic link to plugin in release archive (tried versions 0.2.4 and 0.2.3). There is no actual file
 
![2022-02-07_02-11](https://user-images.githubusercontent.com/36517882/152705562-81101e3c-ae77-4723-9338-d860b9e48f35.png)

**Comment by Qufyy** [comment]
Oops, sorry. I updated the archive.
